# logging_config.yaml
version: 1
formatters:
  briefFormatter:
    format: "%(message)s"
  preciseFormatter:
    format: "%(asctime)s [%(levelname)s] %(name)s: %(message)s"
    # format: "%(asctime)s [%(levelname)s] %(message)s"
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: preciseFormatter
  file:
    class: logging.FileHandler
    filename: output.log
    level: DEBUG
    formatter: preciseFormatter
    encoding: utf-8
loggers:
  clustering:
    level: DEBUG
    handlers: [console, file]
    propagate: no
